version: "3.5"
services:
  nats:
    image: nats
    ports:
      - '5222:4222'
      - '7222:6222'
      - "9222:8222"

  redis:
    image: redis:7.0

  api:
    build:
      context: ./api
    restart: always
    env_file:
      - api/.env
    depends_on:
      - redis
      - nats

  extractor:
    build:
      context: ./extractor
    restart: always
    env_file:
      - extractor/.env
    volumes:
      - "./models:/app/models"
    depends_on:
      - redis
      - nats

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_HTTP_URL: 'http://localhost:3000'
        REACT_APP_WS_URL: 'ws://localhost:3000'
    volumes:
      - "./client:/usr/src/app/my-app"

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:80"
    depends_on:
      - api
      - client